### ISSUE TITLE
[BUG?] Save & Close exited the App

### ISSUE THREAD

**Issue by pc-v2** [unchihugo/FluentFlyout#2]
Save & Close exited the App. Is this normal behavior?

**Comment by unchihugo** [comment]
Thank you for reporting this! Pressing "Save & Close" in settings should only close the settings window, not the whole app. Could you provide a few more details so I can look into it?

1. What version of FluentFlyout are you using?
2. Could you share the steps you followed leading up to this issue? (edited forms, etc.)
3. If possible, could you check Windows Event Viewer > Windows Logs > Application and share the errors on FluentFlyout when the issue happened?

Any extra info would be really helpful. Thanks in advance!
