### ISSUE TITLE
Add More Flyouts 

### ISSUE THREAD

**Issue by leviathanaxeislit** [unchihugo/FluentFlyout#3]
It would be great if you add more flyouts like Brightness and Airplane mode, Lock keys and Insert/Overtype

It could fully replace modernflyouts for me and be the defacto application.

**Comment by unchihugo** [comment]
Hi! What type of flyouts would you want implemented specifically? Thank you :)

**Comment by leviathanaxeislit** [comment]
> Hi! What type of flyouts would you want implemented specifically? Thank you :)

Displaying when caps lock is turned on or off which is helpful for laptops without osd notifications by OEM

u could take this [repo](https://github.com/ModernFlyouts-Community/ModernFlyouts) as reference.
