### ISSUE TITLE
[BUG] - Lock keys is activated even if I deactivate it

### ISSUE THREAD

**Issue by Yasunaii** [unchihugo/FluentFlyout#35]
# Describe the bug
Lock keys is activated even if I deactivate it

# To Reproduce
Well, I wasn't shocked, and then I wanted to deactivate it at some point, but it was already deactivated...

# Expected behavior
Whether the button deactivates or activates the

# Video

https://github.com/user-attachments/assets/ff683d8c-ad1b-4060-8812-e919b444fa90

ps: I've also discovered the new icon, which isn't bad even if I prefer the pretty logo!

**Comment by Ciarkol15** [comment]
+1 , also happends with Next up flyout, next bug flyout dont change current playing, u have to close program to change the soruce of sound.
FEATURE REQUEST
Can be added a possibility to change source of sound that is currently playing, something like in windows action center.
![Zrzut ekranu 2024-11-12 182008](https://github.com/user-attachments/assets/9b6b0192-21ce-4a8b-b142-f9cdcb00476d)

**Comment by Yuzuctus** [comment]
You should create an independent post for your feature request, it looks nice.

**Comment by unchihugo** [comment]
Hey everyone, thanks for reporting this issue!
seems like I made a small logic mistake in the code when I added the fullscreen check, I'll fix it asap and release a hotfix soon :)

**Comment by unchihugo** [comment]
Released an update that fixes this issue at [version 1.3.2](https://github.com/unchihugo/FluentFlyout/releases/latest) :)
