### ISSUE TITLE
[BUG] Settings reset after restart

### ISSUE THREAD

**Issue by 301nav** [unchihugo/FluentFlyout#39]
**Describe the bug**
Settings such as Windows 11-style icon, flyout position, and flyout duration reset to default after the computer restarts

**To Reproduce**
1. Change setting(s) such as flyout position, duration, taskbar icon
2. Restart computer
3. Open FluentFlyout settings or use media controls to see flyout - original position, duration are used instead

**Expected behavior**
The user settings should have retained after restart

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 23H2

**Comment by unchihugo** [comment]
Hi! Thank you for reporting this! I haven't seen this behavior myself, but I do know that user settings might reset on updates, something I'd like to solve soon. 

Could FluentFlyout perhaps have auto updated after you had restarted your computer? I have released an update a few days ago (v1.3.2) that could explain the reset.

Feel free to tell me if the settings do reset after a restart without updating!

**Comment by 301nav** [comment]
That might have been it! I just did another restart and my settings were retained. Thanks for the help
