### ISSUE TITLE
[BUG]Issue with fullscreen applications

### ISSUE THREAD

**Issue by Nex457** [unchihugo/FluentFlyout#5]
While playing game for example Forza Horizon 5, bringing up flyout causes its animation to lag and be slow (disabling animation fixes problem), it causes loss of focus on certain application, bringing up to main menu or causing app to run on lower fps during flyout.

To Reproduce
Try with any application, you can try with fh5 if you have it.

Expected behavior
To be smooth, like Window's volume flyout for example if possible.

 - OS: Windows 11 24h2
 - Version v1.2.2.0

**Comment by unchihugo** [comment]
I'll definitely have a look at the focusing behavior. Thank you!

By the way, how high is your CPU usage while playing FH5?

**Comment by Nex457** [comment]
20-40%, i am on ryzen 5 5600 and forza is more gpu intensive then cpu
